### ISSUE TITLE
CS2X current state?

### ISSUE THREAD

**Issue by LostLinky** [reignstudios/CS2X#4]
Great project! :)

1. CS2X is still being developed?
2. Is already in an usable state for production? What are the current limitations?

Thank you!

**Comment by zezba9000** [comment]
* I've started a new job and so stuff has slowed a bit (wish I could spend all my time here).
* Its not in a production state.
* I'm re-looking into some IL2X stuff to see if it offers features faster for CPU targets (not GPUs)
