### ISSUE TITLE
What's the difference between corert and CS2X?

### ISSUE THREAD

**Issue by GNUfan42** [reignstudios/CS2X#5]
There's a .NET runtime names [CoreRT](https://github.com/dotnet/corert), it has a backend calls CppCodeGen, which can also transcompile C# to C(Okay, actually that's C++). Has anyone used it? If yes, please tell me whether I should use it or CS2X.

Thank you!

**Comment by zezba9000** [comment]
CoreRT translates IL instructions while CS2X translates/compiles C# syntax to a target. Neither are ready for production use.

IL2X is closer to CoreRT but translates to C89 for portability & performance: https://github.com/reignstudios/IL2X
IL2X is a runtime subset & still being made. It should be as fast as C & end up allowing for more modern C# lang features.
